// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '***REMOVED***',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    authDomain: '***REMOVED***.firebaseapp.com',
    storageBucket: '***REMOVED***.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:android:f7fdd2f8b97cc53c55fd3f',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:ios:8f37b9ead472c53f55fd3f',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
    iosBundleId: '***REMOVED***',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '***REMOVED***',
    appId: '1:***REMOVED***:ios:d10d47af231f540355fd3f',
    messagingSenderId: '***REMOVED***',
    projectId: '***REMOVED***',
    storageBucket: '***REMOVED***.appspot.com',
    iosBundleId: '***REMOVED***.RunnerTests',
  );
}
