// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlMXee1YgD7io4qYwdVkAfikLiCjEWxTw',
    appId: '1:447245725870:web:1b6228fdbbda4bcd55fd3f',
    messagingSenderId: '447245725870',
    projectId: 'simple-messenger-53bdb',
    authDomain: 'simple-messenger-53bdb.firebaseapp.com',
    storageBucket: 'simple-messenger-53bdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyOpi3aZ3mYREDzMRxwqw0c7UO0l6epBU',
    appId: '1:447245725870:android:f7fdd2f8b97cc53c55fd3f',
    messagingSenderId: '447245725870',
    projectId: 'simple-messenger-53bdb',
    storageBucket: 'simple-messenger-53bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRmkLJJi_x6faefwTT0eOoDNc3RA3r8ck',
    appId: '1:447245725870:ios:8f37b9ead472c53f55fd3f',
    messagingSenderId: '447245725870',
    projectId: 'simple-messenger-53bdb',
    storageBucket: 'simple-messenger-53bdb.appspot.com',
    iosBundleId: 'com.example.simpleMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRmkLJJi_x6faefwTT0eOoDNc3RA3r8ck',
    appId: '1:447245725870:ios:d10d47af231f540355fd3f',
    messagingSenderId: '447245725870',
    projectId: 'simple-messenger-53bdb',
    storageBucket: 'simple-messenger-53bdb.appspot.com',
    iosBundleId: 'com.example.simpleMessenger.RunnerTests',
  );
}
